# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: app/Dockerfile
    
    ports:
      - 5281:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  wapp:
    container_name: wapp
    image: wapp
    build:
      context: .
      dockerfile: wapp/Dockerfile
    ports:
      - 5043:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw